### ISSUE TITLE
Serializable

### ISSUE THREAD

**Issue by kovacsmarcell** [IITeam-Rocket/IceField#25]
Legyenek a dolgok Serializable-k, és legyen az Environmentben egy függvény ami egy megadott file névbe kiírja az instance nevű Singleton tagváltozóját. Legyen egy ugyanilyen függvény beolvasásra is.
A beolvasás és a kiírás is szerializálva történjen.

**Comment by Tophyan1** [comment]
Megcsináltam, hogy minden Serializable, de az Environment függvényeit megírod?

**Comment by kovacsmarcell** [comment]
Megcsináltam nagy szopással.
