### ISSUE TITLE
MapBuilding

### ISSUE THREAD

**Issue by Tophyan1** [IITeam-Rocket/IceField#29]
Tegyünk már be egy parancsot, ami felépíti a Goldschmidt által adott pályát.
Akkor nem kell minden teszteset elején mebásolni azt a szart.

**Comment by kovacsmarcell** [comment]
"input map.txt" pont ez csinálja, csak annyi a gond, hogy nem tudja, hogy kinek adja vissza az inputot, miután lefutott, épp a végére beírtam, hogy "input console". De azt beleírhatom, hogy legyen vmi "input last" és akkor az utolsónak adja ami meghívta.

**Comment by kovacsmarcell** [comment]
Másik javaslat a tesztek előtt egyszer lefuttatod az alábbit:

```
input map.txt
save mapstatus.txt
```


és minden teszt elején visszatöltöd ezt a teljes játék állást az alábbi módon:
`
load mapstatus.txt
`
