### ISSUE TITLE
Nem eszi meg a medve az embereket, meg írja ki ha valakit meg enne de megmenekül

### ISSUE THREAD

**Issue by kovacsmarcell** [IITeam-Rocket/IceField#31]
Próbáld ki:

```
input map.txt
input test1.txt
```

Az egyik lépésbn meg kéne ennie a medvének az egyiket, de nem történik, meg azonnal vége is kéne hogy érjen a game és kéne output, hogy megette. Az előző doksiban látod mit léne outputnak.

Tesztesetek amik ehhez kapcsolódnak (mind fail):
8.
29.
30.

**Comment by Tophyan1** [comment]
Átraktam a támadást a moveTo()-ba, elvileg jónak kell lennie
